import type { CollectorRow, OverviewResponse } from "@/api";

export const showcaseOverviewMock: OverviewResponse = {
  quick_analysis: {
    headline: "Runtime is stable — one open incident and two services need attention",
    risk_level: "low",
    containers_running: 2,
    process_sample_size: 148,
    code_projects_found: 4,
    mode: "operator",
    ai_role: "investigator",
  },
  experience: {
    mode: "operator",
    ai_role: "investigator",
    suggest_safe_actions: true,
    execute_actions: false,
    show_raw_evidence_by_default: false,
  },
  workspace_projects: [
    { path: "D:/MYFiles/Projects/py/Inferra", kind: "rust", marker: "Cargo.toml" },
    { path: "D:/MYFiles/Projects/py/Inferra/src/web/frontend", kind: "node", marker: "package.json" },
    { path: "D:/MYFiles/Projects/demo-api", kind: "python", marker: "pyproject.toml" },
    { path: "D:/MYFiles/Projects/shop-ui", kind: "node", marker: "package.json" },
  ],
  runtime: {
    hostname: "dev-machine",
    containers: [
      { name: "inferra-ci", image: "inferra:0.3.0", state: "running" },
      { name: "ollama", image: "ollama/ollama:latest", state: "running" },
    ],
    processes: [],
  },
  dashboard: {
    health: {
      status: "ok",
      active_incidents: 1,
      queue_depth: 0,
      collector_errors: 0,
      degraded: false,
      storage_writes_ok: true,
      ai_enabled: true,
      ai_available: true,
      ai_reason: "Ollama reachable · gemma4:e4b",
    },
    incidents: [
      {
        incident_id: "inc_7f2a91c4",
        state: "investigating",
        severity: 3,
        primary_service: "inferra-api",
        affected_services: ["inferra-api", "collectors"],
        created_at: new Date(Date.now() - 1000 * 60 * 42).toISOString(),
        updated_at: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
        event_count: 24,
        latest_trace_summary: {
          trace_id: "4b8e2f1c9d0a3e7b6c5d4a2f1e0b9c8",
          event_count: 12,
          service_id: "inferra-api",
          source_type: "app",
          signal_kind: "error_burst",
          sample_message: "collector emit retry under queue backpressure",
        },
      },
      {
        incident_id: "inc_31be08aa",
        state: "resolved",
        severity: 2,
        primary_service: "windows-service",
        affected_services: ["windows-service"],
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
        updated_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
        event_count: 9,
      },
    ],
    services: [
      {
        service_id: "inferra-api",
        status: "elevated",
        event_count: 412,
        error_count: 18,
        last_event_at: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
      },
      {
        service_id: "inferra-cli",
        status: "healthy",
        event_count: 96,
        error_count: 0,
        last_event_at: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
      },
      {
        service_id: "workspace-scanner",
        status: "degraded",
        event_count: 58,
        error_count: 4,
        last_event_at: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
      },
      {
        service_id: "docker-engine",
        status: "healthy",
        event_count: 203,
        error_count: 1,
        last_event_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
      },
      {
        service_id: "ollama",
        status: "healthy",
        event_count: 44,
        error_count: 0,
        last_event_at: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
      },
      {
        service_id: "windows-service",
        status: "healthy",
        event_count: 1280,
        error_count: 6,
        last_event_at: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
      },
    ],
    event_rate: [
      { timestamp: hoursAgo(11), total: 42, warn: 8, error: 2, critical: 0 },
      { timestamp: hoursAgo(10), total: 38, warn: 6, error: 1, critical: 0 },
      { timestamp: hoursAgo(9), total: 51, warn: 11, error: 3, critical: 0 },
      { timestamp: hoursAgo(8), total: 47, warn: 9, error: 2, critical: 0 },
      { timestamp: hoursAgo(7), total: 63, warn: 14, error: 5, critical: 1 },
      { timestamp: hoursAgo(6), total: 55, warn: 12, error: 4, critical: 0 },
      { timestamp: hoursAgo(5), total: 49, warn: 10, error: 3, critical: 0 },
      { timestamp: hoursAgo(4), total: 44, warn: 7, error: 2, critical: 0 },
      { timestamp: hoursAgo(3), total: 58, warn: 13, error: 4, critical: 0 },
      { timestamp: hoursAgo(2), total: 52, warn: 11, error: 3, critical: 0 },
      { timestamp: hoursAgo(1), total: 46, warn: 8, error: 2, critical: 0 },
      { timestamp: hoursAgo(0), total: 41, warn: 7, error: 1, critical: 0 },
    ],
    severity_counts: { info: 1842, warn: 312, error: 48, critical: 3 },
  },
};

export const showcaseCollectorsMock: CollectorRow[] = [
  {
    collector_id: "windows_event_log",
    status: "running",
    source_type: "windows_event",
    is_running: true,
    events_emitted: 1280,
    events_per_second: 0.4,
    error_count: 0,
  },
  {
    collector_id: "host_resources",
    status: "running",
    source_type: "host",
    is_running: true,
    events_emitted: 412,
    events_per_second: 0.1,
    error_count: 0,
  },
  {
    collector_id: "workspace_scanner",
    status: "running",
    source_type: "workspace",
    is_running: true,
    events_emitted: 58,
    events_per_second: 0.02,
    error_count: 0,
  },
];

function hoursAgo(hours: number) {
  return new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();
}
