apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "inferra.fullname" . }}-data
spec:
  {{- if .Values.storage.storageClassName }}
  storageClassName: {{ .Values.storage.storageClassName | quote }}
  {{- end }}
  accessModes:
{{ toYaml .Values.storage.accessModes | indent 4 }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
