{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "inferra.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "inferra.name" . }}
    {{- range $key, $value := .Values.serviceMonitor.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "inferra.name" . }}
  endpoints:
    - port: http
      interval: {{ .Values.serviceMonitor.interval | quote }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout | quote }}
      path: {{ .Values.serviceMonitor.path | quote }}
{{- end }}
